version: '2'
services:
    jdapp-app:
        image: jdapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jdapp-mysql:3306/jdapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdapp-mysql:
        extends:
            file: mysql.yml
            service: jdapp-mysql
